// Render FreeRADIUS clients.conf from the configured NAS shared secret.
//
// Stock FreeRADIUS only trusts localhost, so the MikroTik router (a different IP)
// is rejected with "Ignoring request from unknown client". We rewrite clients.conf
// at boot (db-init, before radiusd starts) so the router — and any LAN NAS — is
// accepted using the same shared secret the rest of the system already uses (the
// value autoconfig sets on the router and that CoA signs with).
//
// The accepted source range defaults to "everything": this is a single-tenant LAN
// appliance and the shared secret is the real gate. Scope it to the hotspot subnet
// with TIKSPOT_RADIUS_CLIENT_NET / _NET6 if you prefer a tighter bound.

import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { ensureNasSecret } from './nas.js';

const RADDB_DIR = process.env.TIKSPOT_RADDB_DIR ?? '/etc/raddb';
const CLIENT_NET = process.env.TIKSPOT_RADIUS_CLIENT_NET ?? '0.0.0.0/0';
const CLIENT_NET6 = process.env.TIKSPOT_RADIUS_CLIENT_NET6 ?? '::/0';

function block(name, addrLine, secret) {
  return `client ${name} {\n\t${addrLine}\n\tsecret = ${secret}\n\tproto = *\n}\n`;
}

export function renderClientsConf(secret) {
  return (
    '# Generated by Tikspot at boot — do not edit (regenerated on every start).\n' +
    '# Trusts localhost plus the configured LAN range, all using the NAS secret.\n' +
    '# More-specific localhost entries win for loopback; the /0 client catches the rest.\n' +
    block('localhost', 'ipaddr = 127.0.0.1', secret) +
    block('localhost_ipv6', 'ipv6addr = ::1', secret) +
    block('tikspot_net', `ipaddr = ${CLIENT_NET}`, secret) +
    block('tikspot_net6', `ipv6addr = ${CLIENT_NET6}`, secret)
  );
}

// Write clients.conf if the raddb dir exists (i.e. inside the container). Returns
// true if written, false where FreeRADIUS isn't installed — so db-init stays
// usable in plain dev/test environments without a raddb tree.
export function writeClientsConf(secret) {
  if (!secret) return false;
  if (!fs.existsSync(RADDB_DIR)) return false;
  fs.writeFileSync(path.join(RADDB_DIR, 'clients.conf'), renderClientsConf(secret));
  return true;
}

// Restart radiusd so a freshly-written clients.conf takes effect. FreeRADIUS does
// NOT reload client/secret definitions on SIGHUP, so we bounce the supervised
// longrun: SIGTERM, which the s6 supervisor follows by restarting it (the wanted
// state stays "up"). No-op where s6 isn't present (dev/test). Returns true on a
// clean signal.
export function reloadRadiusd() {
  for (const bin of ['/command/s6-svc', 's6-svc']) {
    try {
      const r = spawnSync(bin, ['-t', '/run/service/radiusd'], { timeout: 5000 });
      if (r.status === 0) return true;
    } catch {
      /* try the next candidate path */
    }
  }
  return false;
}

// Re-render clients.conf from the current NAS secret and reload radiusd, so a
// secret set/changed at runtime (e.g. via the setup wizard or Auto-configure)
// takes effect live — keeping the container's accepted secret in lock-step with
// what the router was told, without needing a container restart.
export function applyNasSecret(db) {
  const wrote = writeClientsConf(ensureNasSecret(db));
  const reloaded = wrote ? reloadRadiusd() : false;
  return { wrote, reloaded };
}
